# Contract tests for the pure policy renderer. No provider and no credentials:
# the module has no resources, and every ARN is a plain input, so every
# document can be asserted in full at plan time. The root cannot do this
# itself (its ARNs are unknown until apply), which is why the documents live
# here.
#
# The `golden` run compares documents byte for byte with the ones v0.1.0 built
# as root locals (generated by evaluating v0.1.0's locals.tf with the same
# ARNs). A change to a statement is a change to the live policy of a backend
# that protects state: update the golden strings only as a reviewed decision.
#
# Reviewed deviation (1.0.1): a replicated tier's primary key policy carries one
# extra statement, KeyReplication (kms:ReplicateKey for the key administrators),
# appended after StateEncryptionUse. v0.1.0 omitted it, so aws_kms_replica_key
# could not be created against a key policy with no account-root statement.
# Every other document, including a non-replicated tier's key policy, is still
# byte-identical to v0.1.0.

variables {
  tiers = ["dev", "staging", "prod"]
  state_access_principal_arns = [
    "arn:aws:iam::111122223333:role/ci-terraform",
    "arn:aws:iam::111122223333:role/break-glass",
  ]
  key_administrator_arns = ["arn:aws:iam::111122223333:role/key-admin"]
  bucket_arns = {
    dev     = "arn:aws:s3:::test-platform-dev-tfstate"
    staging = "arn:aws:s3:::test-platform-staging-tfstate"
    prod    = "arn:aws:s3:::test-platform-prod-tfstate"
  }
  key_arns = {
    dev     = "arn:aws:kms:us-east-2:111122223333:key/mrk-dev"
    staging = "arn:aws:kms:us-east-2:111122223333:key/mrk-staging"
    prod    = "arn:aws:kms:us-east-2:111122223333:key/mrk-prod"
  }
  replication_role_arns = {
    staging = "arn:aws:iam::111122223333:role/test-platform-staging-terraform-state-replication"
    prod    = "arn:aws:iam::111122223333:role/test-platform-prod-terraform-state-replication"
  }
  replica_bucket_arns = {
    staging = "arn:aws:s3:::test-platform-staging-tfstate-replica"
    prod    = "arn:aws:s3:::test-platform-prod-tfstate-replica"
  }
  replica_key_arns = {
    staging = "arn:aws:kms:us-west-2:111122223333:key/mrk-staging"
    prod    = "arn:aws:kms:us-west-2:111122223333:key/mrk-prod"
  }
}

run "golden_documents_match_v0_1_0_byte_for_byte_except_key_replication" {
  command = plan

  assert {
    condition     = output.key_policies["dev"] == "{\"Statement\":[{\"Action\":[\"kms:Create*\",\"kms:Describe*\",\"kms:Enable*\",\"kms:Get*\",\"kms:List*\",\"kms:Put*\",\"kms:Revoke*\",\"kms:Update*\",\"kms:Disable*\",\"kms:Delete*\",\"kms:TagResource\",\"kms:UntagResource\",\"kms:ScheduleKeyDeletion\",\"kms:CancelKeyDeletion\"],\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"arn:aws:iam::111122223333:role/key-admin\"]},\"Resource\":\"*\",\"Sid\":\"KeyAdministration\"},{\"Action\":[\"kms:Decrypt\",\"kms:DescribeKey\",\"kms:Encrypt\",\"kms:GenerateDataKey*\",\"kms:ReEncrypt*\"],\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"arn:aws:iam::111122223333:role/break-glass\",\"arn:aws:iam::111122223333:role/ci-terraform\"]},\"Resource\":\"*\",\"Sid\":\"StateEncryptionUse\"}],\"Version\":\"2012-10-17\"}"
    error_message = "The non-replicated tier's key policy must be byte-identical to v0.1.0."
  }

  assert {
    condition     = output.key_policies["prod"] == "{\"Statement\":[{\"Action\":[\"kms:Create*\",\"kms:Describe*\",\"kms:Enable*\",\"kms:Get*\",\"kms:List*\",\"kms:Put*\",\"kms:Revoke*\",\"kms:Update*\",\"kms:Disable*\",\"kms:Delete*\",\"kms:TagResource\",\"kms:UntagResource\",\"kms:ScheduleKeyDeletion\",\"kms:CancelKeyDeletion\"],\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"arn:aws:iam::111122223333:role/key-admin\"]},\"Resource\":\"*\",\"Sid\":\"KeyAdministration\"},{\"Action\":[\"kms:Decrypt\",\"kms:DescribeKey\",\"kms:Encrypt\",\"kms:GenerateDataKey*\",\"kms:ReEncrypt*\"],\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"arn:aws:iam::111122223333:role/break-glass\",\"arn:aws:iam::111122223333:role/ci-terraform\",\"arn:aws:iam::111122223333:role/test-platform-prod-terraform-state-replication\"]},\"Resource\":\"*\",\"Sid\":\"StateEncryptionUse\"},{\"Action\":[\"kms:ReplicateKey\"],\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"arn:aws:iam::111122223333:role/key-admin\"]},\"Resource\":\"*\",\"Sid\":\"KeyReplication\"}],\"Version\":\"2012-10-17\"}"
    error_message = "The replicated tier's key policy must be v0.1.0's plus the KeyReplication statement, byte for byte."
  }

  assert {
    condition     = output.replica_key_policies["prod"] == "{\"Statement\":[{\"Action\":[\"kms:Create*\",\"kms:Describe*\",\"kms:Enable*\",\"kms:Get*\",\"kms:List*\",\"kms:Put*\",\"kms:Revoke*\",\"kms:Update*\",\"kms:Disable*\",\"kms:Delete*\",\"kms:TagResource\",\"kms:UntagResource\",\"kms:ScheduleKeyDeletion\",\"kms:CancelKeyDeletion\"],\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"arn:aws:iam::111122223333:role/key-admin\"]},\"Resource\":\"*\",\"Sid\":\"KeyAdministration\"},{\"Action\":[\"kms:Decrypt\",\"kms:DescribeKey\",\"kms:Encrypt\",\"kms:GenerateDataKey*\",\"kms:ReEncrypt*\"],\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"arn:aws:iam::111122223333:role/break-glass\",\"arn:aws:iam::111122223333:role/ci-terraform\",\"arn:aws:iam::111122223333:role/test-platform-prod-terraform-state-replication\"]},\"Resource\":\"*\",\"Sid\":\"StateReplicaEncryptionUse\"}],\"Version\":\"2012-10-17\"}"
    error_message = "The replica key policy must be byte-identical to v0.1.0."
  }

  assert {
    condition     = output.bucket_policies["dev"] == "{\"Statement\":[{\"Action\":\"s3:*\",\"Condition\":{\"Bool\":{\"aws:SecureTransport\":\"false\"}},\"Effect\":\"Deny\",\"Principal\":\"*\",\"Resource\":[\"arn:aws:s3:::test-platform-dev-tfstate\",\"arn:aws:s3:::test-platform-dev-tfstate/*\"],\"Sid\":\"DenyInsecureTransport\"},{\"Action\":\"s3:*\",\"Condition\":{\"ArnNotEquals\":{\"aws:PrincipalArn\":[\"arn:aws:iam::111122223333:role/break-glass\",\"arn:aws:iam::111122223333:role/ci-terraform\"]}},\"Effect\":\"Deny\",\"Principal\":\"*\",\"Resource\":[\"arn:aws:s3:::test-platform-dev-tfstate\",\"arn:aws:s3:::test-platform-dev-tfstate/*\"],\"Sid\":\"DenyPrincipalsOutsideStateRoles\"},{\"Action\":[\"s3:GetBucketLocation\",\"s3:GetBucketVersioning\",\"s3:ListBucket\"],\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"arn:aws:iam::111122223333:role/break-glass\",\"arn:aws:iam::111122223333:role/ci-terraform\"]},\"Resource\":\"arn:aws:s3:::test-platform-dev-tfstate\",\"Sid\":\"AllowStateBucketMetadata\"},{\"Action\":[\"s3:DeleteObject\",\"s3:GetObject\",\"s3:PutObject\"],\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"arn:aws:iam::111122223333:role/break-glass\",\"arn:aws:iam::111122223333:role/ci-terraform\"]},\"Resource\":\"arn:aws:s3:::test-platform-dev-tfstate/*\",\"Sid\":\"AllowStateAndLockObjects\"}],\"Version\":\"2012-10-17\"}"
    error_message = "The non-replicated tier's bucket policy must be byte-identical to v0.1.0."
  }

  assert {
    condition     = output.bucket_policies["prod"] == "{\"Statement\":[{\"Action\":\"s3:*\",\"Condition\":{\"Bool\":{\"aws:SecureTransport\":\"false\"}},\"Effect\":\"Deny\",\"Principal\":\"*\",\"Resource\":[\"arn:aws:s3:::test-platform-prod-tfstate\",\"arn:aws:s3:::test-platform-prod-tfstate/*\"],\"Sid\":\"DenyInsecureTransport\"},{\"Action\":\"s3:*\",\"Condition\":{\"ArnNotEquals\":{\"aws:PrincipalArn\":[\"arn:aws:iam::111122223333:role/break-glass\",\"arn:aws:iam::111122223333:role/ci-terraform\",\"arn:aws:iam::111122223333:role/test-platform-prod-terraform-state-replication\"]}},\"Effect\":\"Deny\",\"Principal\":\"*\",\"Resource\":[\"arn:aws:s3:::test-platform-prod-tfstate\",\"arn:aws:s3:::test-platform-prod-tfstate/*\"],\"Sid\":\"DenyPrincipalsOutsideStateRoles\"},{\"Action\":[\"s3:GetBucketLocation\",\"s3:GetBucketVersioning\",\"s3:ListBucket\"],\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"arn:aws:iam::111122223333:role/break-glass\",\"arn:aws:iam::111122223333:role/ci-terraform\"]},\"Resource\":\"arn:aws:s3:::test-platform-prod-tfstate\",\"Sid\":\"AllowStateBucketMetadata\"},{\"Action\":[\"s3:DeleteObject\",\"s3:GetObject\",\"s3:PutObject\"],\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"arn:aws:iam::111122223333:role/break-glass\",\"arn:aws:iam::111122223333:role/ci-terraform\"]},\"Resource\":\"arn:aws:s3:::test-platform-prod-tfstate/*\",\"Sid\":\"AllowStateAndLockObjects\"}],\"Version\":\"2012-10-17\"}"
    error_message = "The replicated tier's bucket policy must be byte-identical to v0.1.0."
  }

  assert {
    condition     = output.replica_bucket_policies["prod"] == "{\"Statement\":[{\"Action\":\"s3:*\",\"Condition\":{\"Bool\":{\"aws:SecureTransport\":\"false\"}},\"Effect\":\"Deny\",\"Principal\":\"*\",\"Resource\":[\"arn:aws:s3:::test-platform-prod-tfstate-replica\",\"arn:aws:s3:::test-platform-prod-tfstate-replica/*\"],\"Sid\":\"DenyInsecureTransport\"},{\"Action\":\"s3:*\",\"Condition\":{\"ArnNotEquals\":{\"aws:PrincipalArn\":[\"arn:aws:iam::111122223333:role/break-glass\",\"arn:aws:iam::111122223333:role/ci-terraform\",\"arn:aws:iam::111122223333:role/test-platform-prod-terraform-state-replication\"]}},\"Effect\":\"Deny\",\"Principal\":\"*\",\"Resource\":[\"arn:aws:s3:::test-platform-prod-tfstate-replica\",\"arn:aws:s3:::test-platform-prod-tfstate-replica/*\"],\"Sid\":\"DenyPrincipalsOutsideStateRecoveryAndReplicationRoles\"},{\"Action\":[\"s3:GetBucketLocation\",\"s3:GetBucketVersioning\",\"s3:ListBucket\"],\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"arn:aws:iam::111122223333:role/break-glass\",\"arn:aws:iam::111122223333:role/ci-terraform\"]},\"Resource\":\"arn:aws:s3:::test-platform-prod-tfstate-replica\",\"Sid\":\"AllowStateRecoveryBucketMetadata\"},{\"Action\":[\"s3:DeleteObject\",\"s3:GetObject\",\"s3:PutObject\"],\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"arn:aws:iam::111122223333:role/break-glass\",\"arn:aws:iam::111122223333:role/ci-terraform\"]},\"Resource\":\"arn:aws:s3:::test-platform-prod-tfstate-replica/*\",\"Sid\":\"AllowReplicatedStateRecoveryObjects\"}],\"Version\":\"2012-10-17\"}"
    error_message = "The replica bucket policy must be byte-identical to v0.1.0."
  }

  assert {
    condition     = output.replication_policies["prod"] == "{\"Statement\":[{\"Action\":[\"s3:GetReplicationConfiguration\",\"s3:ListBucket\"],\"Effect\":\"Allow\",\"Resource\":\"arn:aws:s3:::test-platform-prod-tfstate\",\"Sid\":\"ReadSourceBucketReplicationConfiguration\"},{\"Action\":[\"s3:GetObjectVersionForReplication\",\"s3:GetObjectVersionAcl\",\"s3:GetObjectVersionTagging\",\"s3:GetObjectRetention\",\"s3:GetObjectLegalHold\"],\"Effect\":\"Allow\",\"Resource\":\"arn:aws:s3:::test-platform-prod-tfstate/*\",\"Sid\":\"ReadSourceObjectVersionsForReplication\"},{\"Action\":[\"s3:ReplicateObject\",\"s3:ReplicateDelete\",\"s3:ReplicateTags\",\"s3:ObjectOwnerOverrideToBucketOwner\"],\"Effect\":\"Allow\",\"Resource\":\"arn:aws:s3:::test-platform-prod-tfstate-replica/*\",\"Sid\":\"WriteReplicatedObjectVersions\"},{\"Action\":[\"kms:Decrypt\",\"kms:GenerateDataKey\"],\"Effect\":\"Allow\",\"Resource\":\"arn:aws:kms:us-east-2:111122223333:key/mrk-prod\",\"Sid\":\"DecryptPrimaryStateKeys\"},{\"Action\":[\"kms:Encrypt\",\"kms:GenerateDataKey\"],\"Effect\":\"Allow\",\"Resource\":\"arn:aws:kms:us-west-2:111122223333:key/mrk-prod\",\"Sid\":\"EncryptReplicaStateKeys\"}],\"Version\":\"2012-10-17\"}"
    error_message = "The replication policy must be byte-identical to v0.1.0."
  }
}

run "every_tier_gets_key_and_bucket_documents_and_only_replicated_tiers_get_replica_documents" {
  command = plan

  assert {
    condition     = toset(keys(output.key_policies)) == toset(["dev", "staging", "prod"]) && toset(keys(output.bucket_policies)) == toset(["dev", "staging", "prod"])
    error_message = "Every tier must have a primary key policy and a primary bucket policy."
  }

  assert {
    condition = (
      toset(keys(output.replica_key_policies)) == toset(["staging", "prod"]) &&
      toset(keys(output.replica_bucket_policies)) == toset(["staging", "prod"]) &&
      toset(keys(output.replication_policies)) == toset(["staging", "prod"])
    )
    error_message = "Only replicated tiers may receive a replica key policy, a replica bucket policy or a replication policy."
  }
}

run "key_policy_separates_administration_from_use" {
  command = plan

  assert {
    condition     = length(jsondecode(output.key_policies["dev"]).Statement) == 2 && jsondecode(output.key_policies["dev"]).Version == "2012-10-17"
    error_message = "A non-replicated tier's key policy must have exactly the administration and the use statement."
  }

  assert {
    condition     = length(jsondecode(output.key_policies["prod"]).Statement) == 3 && jsondecode(output.key_policies["prod"]).Version == "2012-10-17"
    error_message = "A replicated tier's key policy must have exactly the administration, the use and the key replication statement."
  }

  assert {
    condition = (
      jsondecode(output.key_policies["prod"]).Statement[0].Sid == "KeyAdministration" &&
      jsondecode(output.key_policies["prod"]).Statement[0].Effect == "Allow" &&
      jsondecode(output.key_policies["prod"]).Statement[0].Principal.AWS == ["arn:aws:iam::111122223333:role/key-admin"] &&
      jsondecode(output.key_policies["prod"]).Statement[0].Resource == "*"
    )
    error_message = "Key administration must be granted to the key administrators only."
  }

  assert {
    condition = (
      contains(jsondecode(output.key_policies["prod"]).Statement[0].Action, "kms:ScheduleKeyDeletion") &&
      contains(jsondecode(output.key_policies["prod"]).Statement[0].Action, "kms:CancelKeyDeletion") &&
      contains(jsondecode(output.key_policies["prod"]).Statement[0].Action, "kms:Put*") &&
      !contains(jsondecode(output.key_policies["prod"]).Statement[0].Action, "kms:*") &&
      !contains(jsondecode(output.key_policies["prod"]).Statement[0].Action, "kms:Decrypt") &&
      !contains(jsondecode(output.key_policies["prod"]).Statement[0].Action, "kms:Encrypt")
    )
    error_message = "Administration must not include data-plane use, and must not be a wildcard."
  }

  assert {
    condition = (
      jsondecode(output.key_policies["prod"]).Statement[1].Sid == "StateEncryptionUse" &&
      jsondecode(output.key_policies["prod"]).Statement[1].Effect == "Allow" &&
      jsondecode(output.key_policies["prod"]).Statement[1].Action == ["kms:Decrypt", "kms:DescribeKey", "kms:Encrypt", "kms:GenerateDataKey*", "kms:ReEncrypt*"] &&
      jsondecode(output.key_policies["prod"]).Statement[1].Resource == "*"
    )
    error_message = "Key use must be exactly the data-plane actions state encryption needs."
  }

  assert {
    condition = alltrue([
      for statement in jsondecode(output.key_policies["prod"]).Statement : !contains([for principal in flatten([statement.Principal.AWS]) : principal], "*")
    ])
    error_message = "A key policy must never grant to a wildcard principal."
  }
}

run "key_use_covers_the_state_roles_and_the_tiers_own_replication_role_only" {
  command = plan

  assert {
    condition = jsondecode(output.key_policies["dev"]).Statement[1].Principal.AWS == [
      "arn:aws:iam::111122223333:role/break-glass",
      "arn:aws:iam::111122223333:role/ci-terraform",
    ]
    error_message = "A tier without a replica must grant key use to the sorted CI and break-glass roles only."
  }

  assert {
    condition = jsondecode(output.key_policies["prod"]).Statement[1].Principal.AWS == [
      "arn:aws:iam::111122223333:role/break-glass",
      "arn:aws:iam::111122223333:role/ci-terraform",
      "arn:aws:iam::111122223333:role/test-platform-prod-terraform-state-replication",
    ]
    error_message = "A replicated tier must add its own replication role after the state roles."
  }

  assert {
    condition = (
      !strcontains(output.key_policies["dev"], "replication") &&
      !strcontains(output.key_policies["staging"], "test-platform-prod-terraform-state-replication") &&
      !strcontains(output.key_policies["prod"], "test-platform-staging-terraform-state-replication") &&
      !strcontains(output.replica_key_policies["staging"], "test-platform-prod-terraform-state-replication") &&
      !strcontains(output.replica_key_policies["prod"], "test-platform-staging-terraform-state-replication")
    )
    error_message = "One tier's replication role must never appear in another tier's key documents."
  }
}

run "replica_key_policy_mirrors_the_primary_principals_with_its_own_sid" {
  command = plan

  assert {
    condition = (
      length(jsondecode(output.replica_key_policies["prod"]).Statement) == 2 &&
      jsondecode(output.replica_key_policies["prod"]).Statement[0] == jsondecode(output.key_policies["prod"]).Statement[0] &&
      jsondecode(output.replica_key_policies["prod"]).Statement[1].Sid == "StateReplicaEncryptionUse" &&
      jsondecode(output.replica_key_policies["prod"]).Statement[1].Principal == jsondecode(output.key_policies["prod"]).Statement[1].Principal &&
      jsondecode(output.replica_key_policies["prod"]).Statement[1].Action == jsondecode(output.key_policies["prod"]).Statement[1].Action
    )
    error_message = "The replica key policy must administer with the same administrators and grant use to the same principals as the primary key."
  }
}

run "primary_bucket_policy_is_tls_only_and_restricted_to_the_state_roles" {
  command = plan

  assert {
    condition     = length(jsondecode(output.bucket_policies["prod"]).Statement) == 4 && [for statement in jsondecode(output.bucket_policies["prod"]).Statement : statement.Sid] == ["DenyInsecureTransport", "DenyPrincipalsOutsideStateRoles", "AllowStateBucketMetadata", "AllowStateAndLockObjects"]
    error_message = "A bucket policy must have exactly the two denies followed by the two allows, in that order."
  }

  assert {
    condition = (
      jsondecode(output.bucket_policies["prod"]).Statement[0].Effect == "Deny" &&
      jsondecode(output.bucket_policies["prod"]).Statement[0].Principal == "*" &&
      jsondecode(output.bucket_policies["prod"]).Statement[0].Action == "s3:*" &&
      jsondecode(output.bucket_policies["prod"]).Statement[0].Resource == ["arn:aws:s3:::test-platform-prod-tfstate", "arn:aws:s3:::test-platform-prod-tfstate/*"] &&
      jsondecode(output.bucket_policies["prod"]).Statement[0].Condition == { Bool = { "aws:SecureTransport" = "false" } }
    )
    error_message = "The bucket and its objects must deny every non-TLS request from every principal."
  }

  assert {
    condition = (
      jsondecode(output.bucket_policies["prod"]).Statement[1].Effect == "Deny" &&
      jsondecode(output.bucket_policies["prod"]).Statement[1].Principal == "*" &&
      jsondecode(output.bucket_policies["prod"]).Statement[1].Action == "s3:*" &&
      jsondecode(output.bucket_policies["prod"]).Statement[1].Resource == ["arn:aws:s3:::test-platform-prod-tfstate", "arn:aws:s3:::test-platform-prod-tfstate/*"] &&
      jsondecode(output.bucket_policies["prod"]).Statement[1].Condition == { ArnNotEquals = { "aws:PrincipalArn" = [
        "arn:aws:iam::111122223333:role/break-glass",
        "arn:aws:iam::111122223333:role/ci-terraform",
        "arn:aws:iam::111122223333:role/test-platform-prod-terraform-state-replication",
      ] } }
    )
    error_message = "Every principal outside the CI, break-glass and the tier's replication role must be denied all S3 actions."
  }

  assert {
    condition = (
      jsondecode(output.bucket_policies["prod"]).Statement[2].Effect == "Allow" &&
      jsondecode(output.bucket_policies["prod"]).Statement[2].Action == ["s3:GetBucketLocation", "s3:GetBucketVersioning", "s3:ListBucket"] &&
      jsondecode(output.bucket_policies["prod"]).Statement[2].Resource == "arn:aws:s3:::test-platform-prod-tfstate" &&
      jsondecode(output.bucket_policies["prod"]).Statement[3].Effect == "Allow" &&
      jsondecode(output.bucket_policies["prod"]).Statement[3].Action == ["s3:DeleteObject", "s3:GetObject", "s3:PutObject"] &&
      jsondecode(output.bucket_policies["prod"]).Statement[3].Resource == "arn:aws:s3:::test-platform-prod-tfstate/*"
    )
    error_message = "State access must be limited to bucket metadata and to the three object actions the backend needs."
  }

  assert {
    condition = alltrue([
      for index in [2, 3] : jsondecode(output.bucket_policies["prod"]).Statement[index].Principal.AWS == [
        "arn:aws:iam::111122223333:role/break-glass",
        "arn:aws:iam::111122223333:role/ci-terraform",
      ]
    ])
    error_message = "Only the CI and break-glass roles may be allowed access; the replication role is exempt from the deny but is never granted access by the bucket policy."
  }

  assert {
    condition = alltrue([
      for tier in ["dev", "staging", "prod"] : alltrue([
        for statement in jsondecode(output.bucket_policies[tier]).Statement : statement.Effect == "Deny" || can(statement.Principal.AWS)
      ])
    ])
    error_message = "Every Allow statement must name explicit AWS principals; no Allow may use a wildcard principal."
  }
}

run "each_bucket_policy_names_only_its_own_bucket_and_replication_role" {
  command = plan

  assert {
    condition = (
      !strcontains(output.bucket_policies["dev"], "replication") &&
      !strcontains(output.bucket_policies["dev"], "tfstate-replica") &&
      !strcontains(output.bucket_policies["staging"], "test-platform-prod") &&
      !strcontains(output.bucket_policies["prod"], "test-platform-staging") &&
      !strcontains(output.replica_bucket_policies["staging"], "test-platform-prod") &&
      !strcontains(output.replica_bucket_policies["prod"], "test-platform-staging")
    )
    error_message = "A tier's bucket documents must reference neither another tier's bucket nor another tier's replication role."
  }

  assert {
    condition = (
      jsondecode(output.bucket_policies["staging"]).Statement[1].Condition.ArnNotEquals["aws:PrincipalArn"] == [
        "arn:aws:iam::111122223333:role/break-glass",
        "arn:aws:iam::111122223333:role/ci-terraform",
        "arn:aws:iam::111122223333:role/test-platform-staging-terraform-state-replication",
      ] &&
      jsondecode(output.bucket_policies["dev"]).Statement[1].Condition.ArnNotEquals["aws:PrincipalArn"] == [
        "arn:aws:iam::111122223333:role/break-glass",
        "arn:aws:iam::111122223333:role/ci-terraform",
      ]
    )
    error_message = "The deny exemption must list the state roles plus exactly the tier's own replication role, and only the state roles for a tier without a replica."
  }
}

run "replica_bucket_policy_has_the_same_posture_as_the_primary" {
  command = plan

  assert {
    condition     = [for statement in jsondecode(output.replica_bucket_policies["prod"]).Statement : statement.Sid] == ["DenyInsecureTransport", "DenyPrincipalsOutsideStateRecoveryAndReplicationRoles", "AllowStateRecoveryBucketMetadata", "AllowReplicatedStateRecoveryObjects"]
    error_message = "The replica bucket policy must have the two denies followed by the two allows, in that order."
  }

  assert {
    condition = (
      jsondecode(output.replica_bucket_policies["prod"]).Statement[0].Condition == { Bool = { "aws:SecureTransport" = "false" } } &&
      jsondecode(output.replica_bucket_policies["prod"]).Statement[0].Resource == ["arn:aws:s3:::test-platform-prod-tfstate-replica", "arn:aws:s3:::test-platform-prod-tfstate-replica/*"] &&
      jsondecode(output.replica_bucket_policies["prod"]).Statement[1].Condition == { ArnNotEquals = { "aws:PrincipalArn" = [
        "arn:aws:iam::111122223333:role/break-glass",
        "arn:aws:iam::111122223333:role/ci-terraform",
        "arn:aws:iam::111122223333:role/test-platform-prod-terraform-state-replication",
      ] } } &&
      jsondecode(output.replica_bucket_policies["prod"]).Statement[1].Effect == "Deny" &&
      jsondecode(output.replica_bucket_policies["prod"]).Statement[1].Action == "s3:*"
    )
    error_message = "The replica bucket must deny non-TLS requests and every principal outside the state roles and the tier's replication role."
  }

  assert {
    condition = (
      jsondecode(output.replica_bucket_policies["prod"]).Statement[2].Resource == "arn:aws:s3:::test-platform-prod-tfstate-replica" &&
      jsondecode(output.replica_bucket_policies["prod"]).Statement[3].Resource == "arn:aws:s3:::test-platform-prod-tfstate-replica/*" &&
      jsondecode(output.replica_bucket_policies["prod"]).Statement[3].Action == ["s3:DeleteObject", "s3:GetObject", "s3:PutObject"] &&
      jsondecode(output.replica_bucket_policies["prod"]).Statement[2].Principal.AWS == ["arn:aws:iam::111122223333:role/break-glass", "arn:aws:iam::111122223333:role/ci-terraform"] &&
      jsondecode(output.replica_bucket_policies["prod"]).Statement[3].Principal.AWS == ["arn:aws:iam::111122223333:role/break-glass", "arn:aws:iam::111122223333:role/ci-terraform"]
    )
    error_message = "Recovery access to the replica must be limited to the CI and break-glass roles and the same four actions."
  }
}

run "replication_policy_is_scoped_to_one_tiers_buckets_and_keys" {
  command = plan

  assert {
    condition     = [for statement in jsondecode(output.replication_policies["prod"]).Statement : statement.Sid] == ["ReadSourceBucketReplicationConfiguration", "ReadSourceObjectVersionsForReplication", "WriteReplicatedObjectVersions", "DecryptPrimaryStateKeys", "EncryptReplicaStateKeys"]
    error_message = "The replication policy must have exactly the five statements replication needs."
  }

  assert {
    condition = (
      jsondecode(output.replication_policies["prod"]).Statement[0].Resource == "arn:aws:s3:::test-platform-prod-tfstate" &&
      jsondecode(output.replication_policies["prod"]).Statement[1].Resource == "arn:aws:s3:::test-platform-prod-tfstate/*" &&
      jsondecode(output.replication_policies["prod"]).Statement[2].Resource == "arn:aws:s3:::test-platform-prod-tfstate-replica/*" &&
      jsondecode(output.replication_policies["prod"]).Statement[3].Resource == "arn:aws:kms:us-east-2:111122223333:key/mrk-prod" &&
      jsondecode(output.replication_policies["prod"]).Statement[4].Resource == "arn:aws:kms:us-west-2:111122223333:key/mrk-prod"
    )
    error_message = "Each replication statement must name only the tier's own source bucket, replica bucket and keys."
  }

  assert {
    condition = (
      jsondecode(output.replication_policies["prod"]).Statement[2].Action == ["s3:ReplicateObject", "s3:ReplicateDelete", "s3:ReplicateTags", "s3:ObjectOwnerOverrideToBucketOwner"] &&
      jsondecode(output.replication_policies["prod"]).Statement[3].Action == ["kms:Decrypt", "kms:GenerateDataKey"] &&
      jsondecode(output.replication_policies["prod"]).Statement[4].Action == ["kms:Encrypt", "kms:GenerateDataKey"] &&
      contains(jsondecode(output.replication_policies["prod"]).Statement[1].Action, "s3:GetObjectRetention") &&
      contains(jsondecode(output.replication_policies["prod"]).Statement[1].Action, "s3:GetObjectLegalHold")
    )
    error_message = "Replication must read Object Lock metadata from the source and write only replicated versions and encrypt only under the replica key."
  }

  assert {
    condition = alltrue([
      for tier in ["staging", "prod"] : alltrue([
        for statement in jsondecode(output.replication_policies[tier]).Statement : statement.Effect == "Allow" && statement.Resource != "*" && !contains(flatten([statement.Action]), "s3:*") && !contains(flatten([statement.Action]), "kms:*")
      ])
    ])
    error_message = "A replication policy must never use a wildcard resource or a wildcard action."
  }

  assert {
    condition = (
      !strcontains(output.replication_policies["staging"], "prod") &&
      !strcontains(output.replication_policies["prod"], "staging") &&
      !strcontains(output.replication_policies["prod"], "dev")
    )
    error_message = "One tier's replication policy must never reference another tier's buckets or keys."
  }
}

run "a_deployment_without_replicas_renders_no_replica_documents" {
  command = plan

  variables {
    replication_role_arns = {}
    replica_bucket_arns   = {}
    replica_key_arns      = {}
  }

  assert {
    condition     = length(output.replica_key_policies) == 0 && length(output.replica_bucket_policies) == 0 && length(output.replication_policies) == 0
    error_message = "With no replicated tier there must be no replica document."
  }

  assert {
    condition = alltrue([
      for tier in ["dev", "staging", "prod"] : (
        jsondecode(output.key_policies[tier]).Statement[1].Principal.AWS == ["arn:aws:iam::111122223333:role/break-glass", "arn:aws:iam::111122223333:role/ci-terraform"] &&
        jsondecode(output.bucket_policies[tier]).Statement[1].Condition.ArnNotEquals["aws:PrincipalArn"] == ["arn:aws:iam::111122223333:role/break-glass", "arn:aws:iam::111122223333:role/ci-terraform"]
      )
    ])
    error_message = "Without a replication role, every tier's documents must name the state roles only."
  }
}

run "a_single_tier_is_valid" {
  command = plan

  variables {
    tiers                 = ["solo"]
    bucket_arns           = { solo = "arn:aws:s3:::test-platform-solo-tfstate" }
    key_arns              = { solo = "arn:aws:kms:us-east-2:111122223333:key/mrk-solo" }
    replication_role_arns = {}
    replica_bucket_arns   = {}
    replica_key_arns      = {}
  }

  assert {
    condition     = keys(output.key_policies) == ["solo"] && keys(output.bucket_policies) == ["solo"]
    error_message = "A single tier must render exactly one key policy and one bucket policy."
  }
}

run "principal_order_is_deterministic_regardless_of_input_order" {
  command = plan

  variables {
    state_access_principal_arns = [
      "arn:aws:iam::111122223333:role/break-glass",
      "arn:aws:iam::111122223333:role/ci-terraform",
    ]
  }

  assert {
    condition     = output.key_policies["prod"] == "{\"Statement\":[{\"Action\":[\"kms:Create*\",\"kms:Describe*\",\"kms:Enable*\",\"kms:Get*\",\"kms:List*\",\"kms:Put*\",\"kms:Revoke*\",\"kms:Update*\",\"kms:Disable*\",\"kms:Delete*\",\"kms:TagResource\",\"kms:UntagResource\",\"kms:ScheduleKeyDeletion\",\"kms:CancelKeyDeletion\"],\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"arn:aws:iam::111122223333:role/key-admin\"]},\"Resource\":\"*\",\"Sid\":\"KeyAdministration\"},{\"Action\":[\"kms:Decrypt\",\"kms:DescribeKey\",\"kms:Encrypt\",\"kms:GenerateDataKey*\",\"kms:ReEncrypt*\"],\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"arn:aws:iam::111122223333:role/break-glass\",\"arn:aws:iam::111122223333:role/ci-terraform\",\"arn:aws:iam::111122223333:role/test-platform-prod-terraform-state-replication\"]},\"Resource\":\"*\",\"Sid\":\"StateEncryptionUse\"},{\"Action\":[\"kms:ReplicateKey\"],\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"arn:aws:iam::111122223333:role/key-admin\"]},\"Resource\":\"*\",\"Sid\":\"KeyReplication\"}],\"Version\":\"2012-10-17\"}"
    error_message = "Reordering the input set must not change a rendered document."
  }
}

run "partitions_other_than_aws_render_unchanged_structure" {
  command = plan

  variables {
    tiers                       = ["gov"]
    state_access_principal_arns = ["arn:aws-us-gov:iam::111122223333:role/ci-terraform", "arn:aws-us-gov:iam::111122223333:role/break-glass"]
    key_administrator_arns      = ["arn:aws-us-gov:iam::111122223333:role/key-admin"]
    bucket_arns                 = { gov = "arn:aws-us-gov:s3:::test-platform-gov-tfstate" }
    key_arns                    = { gov = "arn:aws-us-gov:kms:us-gov-west-1:111122223333:key/mrk-gov" }
    replication_role_arns       = {}
    replica_bucket_arns         = {}
    replica_key_arns            = {}
  }

  assert {
    condition     = jsondecode(output.bucket_policies["gov"]).Statement[0].Resource == ["arn:aws-us-gov:s3:::test-platform-gov-tfstate", "arn:aws-us-gov:s3:::test-platform-gov-tfstate/*"]
    error_message = "ARNs in another partition must be used as given."
  }
}

run "key_replication_is_granted_on_replicated_primary_keys_to_the_key_administrators_only" {
  command = plan

  assert {
    condition = alltrue([
      for tier in ["staging", "prod"] : jsondecode(output.key_policies[tier]).Statement[2] == {
        Sid       = "KeyReplication"
        Effect    = "Allow"
        Action    = ["kms:ReplicateKey"]
        Resource  = "*"
        Principal = { AWS = ["arn:aws:iam::111122223333:role/key-admin"] }
      }
    ])
    error_message = "A replicated tier's primary key policy must allow exactly kms:ReplicateKey, to the key administrators only."
  }

  assert {
    condition = alltrue(flatten([
      for tier in ["dev", "staging", "prod"] : [
        for statement in jsondecode(output.key_policies[tier]).Statement :
        statement.Sid == "KeyReplication" || !contains(flatten([statement.Action]), "kms:ReplicateKey")
      ]
    ]))
    error_message = "kms:ReplicateKey must appear in the KeyReplication statement only, never in the use statement given to the state and replication roles."
  }

  assert {
    condition     = !strcontains(output.key_policies["dev"], "kms:ReplicateKey")
    error_message = "A non-replicated tier's key policy must not allow kms:ReplicateKey."
  }

  assert {
    condition = alltrue([
      for tier in ["staging", "prod"] : !strcontains(output.replica_key_policies[tier], "kms:ReplicateKey")
    ])
    error_message = "A replica key policy must not allow kms:ReplicateKey; only the primary key is replicated."
  }
}

run "key_replication_follows_every_key_administrator" {
  command = plan

  variables {
    key_administrator_arns = [
      "arn:aws:iam::111122223333:role/key-admin-b",
      "arn:aws:iam::111122223333:role/key-admin-a",
    ]
  }

  assert {
    condition     = jsondecode(output.key_policies["prod"]).Statement[2].Principal.AWS == jsondecode(output.key_policies["prod"]).Statement[0].Principal.AWS
    error_message = "KeyReplication must name exactly the principals of KeyAdministration."
  }

  assert {
    condition     = jsondecode(output.key_policies["prod"]).Statement[2].Principal.AWS == ["arn:aws:iam::111122223333:role/key-admin-a", "arn:aws:iam::111122223333:role/key-admin-b"]
    error_message = "KeyReplication principals must be rendered in a deterministic order."
  }
}
